In [10]:
print("hi")

hi


In [11]:
import pandas as pd


In [12]:
d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df

col1  col2
0     1     3
1     2     4

In [13]:
import numpy as np
a=np.array([1,1,1,1,1])
b=np.array([2,2,2,2,2])
a*b

array([2, 2, 2, 2, 2])

In [14]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [15]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])

In [17]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z


array([[2, 2],
       [2, 2]])

In [18]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [19]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [20]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])